version: '2.1'

defaults: &defaults
  docker:
    - image: cimg/python:3.9
  working_directory: ~/project


prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox


jobs:
  test_gradient_model_py39:
    <<: *defaults
    working_directory: ~/project/packages/gb_regressor
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Run tests with Python 3.9
          command: |
            tox
workflows:
  version: 2
  test-all:
    jobs:
      - test_gradient_model_py39