version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  test_gradient_model_py38:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/project/packages/gb_regressor
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run tests with Python 3.8
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox
  test_ml_api_py38:
    docker:
      - image: cimg/python:3.8
      - image: postgres:15
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: example
          POSTGRES_DB: ml_api_test
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: test_user
      DB_PASSWORD: example
      DB_NAME: ml_api_test
    working_directory: ~/project/packages/ml_api
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run API tests with Python 3.8
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox
workflows:
  version: 2
  test-all:
    jobs:
      - test_gradient_model_py38
      - test_ml_api_py38