version: '3.8'
services:
  ml_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ml_api_dev
    depends_on:
      - db
    ports:
      - "5001:5000"   # expose webserver to localhost host:container
    command: bash -c "make run-service-development"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ml_api_dev
    ports:
      - "7619:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

volumes:
  my_db_data:
